### PR TITLE
Bugfix: fix compile error

### PR DESCRIPTION
**Pull request by neoblackcap**

### CODE REVIEW

**Comment by adwhit** [comment]
Hi, thanks for the PR. Could you explain the point of this change? Bear in mind that the current master is meant to build against `diesel` master.

**Comment by neoblackcap** [comment]
I notice all test case are borken. I compile this with the diesel stable version (1.4.2).

**Comment by adwhit** [comment]
Ok got it. Diesel has made breaking changes since `1.4.2`, and this repo has been updated to work with these changes (I just added a commit to fix CI), so this PR is not needed. If you wish to work with `diesel 1.4.2` please use the `0.4.4` release.

**Comment by neoblackcap** [comment]
OK, got it.

**Pull request closed without merging**
