### PR TITLE
Compatibility with diesel master after 72bfb356

### PR DESCRIPTION
**Pull request by Ten0**
https://github.com/diesel-rs/diesel/pull/2787 introduced ability for diesel CLI to infer unknown SQL types from the Postgres backend, and generate corresponding SQL types.

This PR aims to support plugging into these auto-generated types from the schema, completely removing the need for patching the diesel schema if using the Postgres backend.

The approach is:
 - For Postgres, use the diesel-cli-generated `SqlType` structures.
 - For other backends, keep generating the same structure as before.

### CODE REVIEW

**Comment by adwhit** [comment]
Thanks, this is really cool.

The README/docs will have to change quite a bit to explain these changes. This is unfortunate as the current instructions on `master` still apply to `v1.X`, which means that new users don't have dig to find what they need, and I would like to keep it that way.

So, I am minded to merge these changes, but then rename the branches like:
```
master -> diesel-next
diesel-1 -> master
```

I probably should have done that in the first place, but I didn't realise that `diesel-2` would be a mutli-year project.

What you think?

**Comment by Ten0** [comment]
> So, I am minded to merge these changes, but then rename the branches like:
> 
> ```
> master -> diesel-next
> diesel-1 -> master
> ```

That makes some sense and wouldn't be at all an issue for me.
However we may want to think of:
- That wouldn't be very homogeneous with diesel, which eventually will have a `diesel-1.x` branch, a `diesel-2.x` branch, and a `master` branch
- I'm not sure how many people have their Cargo.toml set to `diesel-derive-enum = { git = "https://github.com/adwhit/diesel-derive-enum" }`, which would all need to update (although that probabl)y wouldn't be very hard for them.
- I feel like the best place for this documentation that is version-specific is actually here:
  - https://crates.io/crates/diesel-derive-enum/1.1.1 (where it already is, and is already release-specific)
  - and here: https://docs.rs/diesel-derive-enum/1.1.1/diesel_derive_enum/`

Overall I think it's pretty hard to guarantee that the master branch's Readme corresponds to the latest released API so it shouldn't be assumed by the users nor be considered a requirement.
I don't have a very strong opinion on this though.

**Comment by adwhit** [comment]
Hi sorry my bad, I let this PR dangle way too long. Would you prefer to merge this first before doing a follow-up or just create a new PR with all the changes in it? I should have time to address it this weekend.

**Comment by Ten0** [comment]
I'd prefer to merge this one first 🙂
I've got the other one ready to be rebased on the merge and opened. 🙂

**Pull request merged**
