### PR TITLE
Screaming-concat case-style.

### PR DESCRIPTION
**Pull request by RalfNorthman**
Possible implementation of #70 

I used the diesel-1-branch since I'm currently using diesel 1.x in my project. I also corrected the attribute string for screaming snake case in the readme table. That typo tripped me up earlier.

### CODE REVIEW

**Comment by adwhit** [comment]
Thanks for the pull request. Am I right to think that this is the same as UPPERCASE? In which case I would prefer to rename to UPPERCASE, I don't think SCREAMINGCONCAT is very common terminology

**Comment by RalfNorthman** [comment]
I wasn't aware of UPPERCASE. If I was I would have called it that instead. Rename is fine with me.

**Comment by RalfNorthman** [comment]
I pushed another commit for the name change. Is that okay or do you want a clean one-commit-PR?

**Comment by adwhit** [comment]
This is now part of the latest release

**Pull request closed without merging**
