### PR TITLE
Compatibility with diesel master after dc2eacd

### PR DESCRIPTION
**Pull request by Ten0**

### CODE REVIEW

**Comment by Ten0** [comment]
(Still need to check on the Sqlite impl as I haven't tested it)

**Comment by Ten0** [comment]
The last fail appears to be a Diesel issue (https://github.com/diesel-rs/diesel/issues/2992) that has probably been present since https://github.com/diesel-rs/diesel/commit/887be77536ae855ade3a85aa3c0875c597d23db6.
We're currently fixing it and adding tests within Diesel to check on this in the future.

**Comment by Ten0** [comment]
woohoo, done! :)

**Comment by adwhit** [comment]
Really appreciate the work you've put in keeping this up-to-date - thanks! Hope we can release this soon.

**Pull request merged**
